# 01 — Base municipale

Source unique : `exctraction of data/output/CSV_final.csv`.

Une ligne = une municipalité, retenue si `MUNICIPIO/TIOC` est non vide (les lignes vides sont
des sous-totaux département / province / total "Amazonía Norte").

- `pop_2001/2012/2024` <- bloc "NÚMERO DE PERSONAS POR FUENTE DE ELECTRICIDAD", sous-colonne "Total"
- `hh_2001/2012/2024` <- bloc "NÚMERO DE VIVIENDAS POR FUENTE DE ELECTRICIDAD", sous-colonne
  "Electricidad total" (2001) ou "Total" (2012, 2024)
- `hhsize_YYYY = pop_YYYY / hh_YYYY`
- `r_pop_0112, r_hh_0112 = 100 * ln(x_2012/x_2001) / 11` (taux annuel %/an), idem `r_..._1224` sur 2012-2024

Aucun index en dur : les colonnes sont repérées par leur en-tête exact.

In [ ]:
import math
import os

import pandas as pd

BASE = os.path.dirname(os.getcwd())
CSV_PATH = os.path.join(BASE, "exctraction of data", "output", "CSV_final.csv")

POP_BLOCK = "NÚMERO DE PERSONAS POR FUENTE DE ELECTRICIDAD"
HH_BLOCK = "NÚMERO DE VIVIENDAS POR FUENTE DE ELECTRICIDAD"

POP_SUBCOL_BY_YEAR = {2001: "Total", 2012: "Total", 2024: "Total"}
HH_SUBCOL_BY_YEAR = {2001: "Electricidad total", 2012: "Total", 2024: "Total"}

EXPECTED_TOTAL_ROW_LABEL = "Amazonía Norte"
EXPECTED_N_MUNICIPIOS = 21
EXPECTED_POP_TOTALS = {2001: 194207, 2012: 267766, 2024: 317517}
EXPECTED_HH_TOTALS = {2001: 37569, 2012: 62360, 2024: 84209}


def find_column(raw_columns, block, year, subcol):
    target = f"{block} | {year} | {subcol}"
    matches = [c for c in raw_columns if c == target]
    assert len(matches) == 1, f"Colonne introuvable ou ambiguë : {target!r} ({len(matches)} correspondance(s))"
    return matches[0]

## 1. Lecture et filtre des municipalités

In [ ]:
raw = pd.read_csv(CSV_PATH, encoding="utf-8")
raw_columns = list(raw.columns)

total_row = raw[raw["MUNICIPIO/TIOC"].isna() & (raw["DEPARTAMENTO"] == EXPECTED_TOTAL_ROW_LABEL)]
municipios = raw[raw["MUNICIPIO/TIOC"].notna() & (raw["MUNICIPIO/TIOC"].astype(str).str.strip() != "")].copy()

assert len(municipios) == EXPECTED_N_MUNICIPIOS, (
    f"Nombre de municipalités retenues = {len(municipios)}, attendu {EXPECTED_N_MUNICIPIOS}. "
    "Vérifier le filtre MUNICIPIO/TIOC non vide (colonnes ou lecture décalées)."
)

out = municipios[["DEPARTAMENTO", "PROVINCIA", "MUNICIPIO/TIOC"]].rename(
    columns={"DEPARTAMENTO": "departamento", "PROVINCIA": "provincia", "MUNICIPIO/TIOC": "municipio"}
).reset_index(drop=True)
municipios = municipios.reset_index(drop=True)
out

   departamento               provincia              municipio
0        La Paz          Abel Iturralde                Ixiamas
1          Beni               Vaca Diez              Riberalta
2          Beni               Vaca Diez           Guayaramerín
3          Beni  General José Ballivián                  Reyes
4          Beni  General José Ballivián             Santa Rosa
5          Beni                  Yacuma             Exaltación
6         Pando          Nicolás Suárez                 Cobija
7         Pando          Nicolás Suárez               Porvenir
8         Pando          Nicolás Suárez               Bolpebra
9         Pando          Nicolás Suárez             Bella Flor
10        Pando                Manuripi            Puerto Rico
11        Pando                Manuripi              San Pedro
12        Pando                Manuripi             Filadelfia
13        Pando           Madre de Dios  Puerto Gonzalo Moreno
14        Pando           Madre de Dios            San Lorenzo
15        Pando           Madre de Dios                   Sena
16        Pando                   Abuná             Santa Rosa
17        Pando                   Abuná                 Ingavi
18        Pando          Federico Román        Nueva Esperanza
19        Pando          Federico Román            Villa Nueva
20        Pando          Federico Román         Santos Mercado

## 2. Colonnes pop / hh par année

In [ ]:
for year, subcol in POP_SUBCOL_BY_YEAR.items():
    col = find_column(raw_columns, POP_BLOCK, year, subcol)
    out[f"pop_{year}"] = municipios[col].astype(float)

for year, subcol in HH_SUBCOL_BY_YEAR.items():
    col = find_column(raw_columns, HH_BLOCK, year, subcol)
    out[f"hh_{year}"] = municipios[col].astype(float)

out

,departamento,provincia,municipio,pop_2001,pop_2012,pop_2024,hh_2001,hh_2012,hh_2024
0,La Paz,Abel Iturralde,Ixiamas,5207.0,8338.0,11330.0,1197.0,2270.0,3306.0
1,Beni,Vaca Diez,Riberalta,73981.0,86903.0,107816.0,13558.0,19588.0,27442.0
2,Beni,Vaca Diez,Guayaramerín,39173.0,40186.0,40130.0,7815.0,9261.0,10891.0
3,Beni,General José Ballivián,Reyes,11016.0,12912.0,11284.0,1815.0,2962.0,3417.0
4,Beni,General José Ballivián,Santa Rosa,8915.0,9297.0,10953.0,1567.0,1976.0,2755.0
5,Beni,Yacuma,Exaltación,6504.0,5996.0,7810.0,1090.0,938.0,1455.0
6,Pando,Nicolás Suárez,Cobija,20873.0,43616.0,51908.0,4923.0,12304.0,15564.0
7,Pando,Nicolás Suárez,Porvenir,3554.0,7653.0,9096.0,831.0,1655.0,2230.0
8,Pando,Nicolás Suárez,Bolpebra,1137.0,2058.0,2338.0,292.0,545.0,802.0
9,Pando,Nicolás Suárez,Bella Flor,2140.0,3550.0,3421.0,497.0,944.0,1235.0
10,Pando,Manuripi,Puerto Rico,3846.0,5639.0,6870.0,728.0,1382.0,1989.0
11,Pando,Manuripi,San Pedro,1079.0,2987.0,3248.0,205.0,611.0,612.0
12,Pando,Manuripi,Filadelfia,2800.0,5534.0,7993.0,590.0,1427.0,2514.0
13,Pando,Madre de Dios,Puerto Gonzalo Moreno,3687.0,7544.0,11760.0,592.0,1026.0,1965.0
14,Pando,Madre de Dios,San Lorenzo,3406.0,7058.0,9602.0,586.0,1342.0,1850.0
15,Pando,Madre de Dios,Sena,2103.0,8161.0,10247.0,398.0,1653.0,2875.0
16,Pando,Abuná,Santa Rosa,1815.0,2183.0,2827.0,278.0,611.0,860.0
17,Pando,Abuná,Ingavi,867.0,1618.0,2545.0,162.0,344.0,649.0
18,Pando,Federico Román,Nueva Esperanza,655.0,1777.0,1572.0,170.0,466.0,489.0
19,Pando,Federico Román,Villa Nueva,968.0,2787.0,2485.0,185.0,589.0,708.0
20,Pando,Federico Román,Santos Mercado,481.0,1969.0,2282.0,90.0,466.0,601.0

## 3. Colonnes calculées — taille des ménages et taux de croissance

In [ ]:
for year in (2001, 2012, 2024):
    out[f"hhsize_{year}"] = out[f"pop_{year}"] / out[f"hh_{year}"]

out["r_pop_0112"] = 100 * (out["pop_2012"] / out["pop_2001"]).apply(math.log) / 11
out["r_pop_1224"] = 100 * (out["pop_2024"] / out["pop_2012"]).apply(math.log) / 12
out["r_hh_0112"] = 100 * (out["hh_2012"] / out["hh_2001"]).apply(math.log) / 11
out["r_hh_1224"] = 100 * (out["hh_2024"] / out["hh_2012"]).apply(math.log) / 12
out

,departamento,provincia,municipio,pop_2001,pop_2012,pop_2024,hh_2001,hh_2012,hh_2024,hhsize_2001,hhsize_2012,hhsize_2024,r_pop_0112,r_pop_1224,r_hh_0112,r_hh_1224
0,La Paz,Abel Iturralde,Ixiamas,5207.0,8338.0,11330.0,1197.0,2270.0,3306.0,4.350042,3.673128,3.427102,4.280177,2.555256,5.817831,3.132993
1,Beni,Vaca Diez,Riberalta,73981.0,86903.0,107816.0,13558.0,19588.0,27442.0,5.456631,4.436543,3.928868,1.463493,1.796946,3.344912,2.809646
2,Beni,Vaca Diez,Guayaramerín,39173.0,40186.0,40130.0,7815.0,9261.0,10891.0,5.012540,4.339272,3.684694,0.232099,-0.011621,1.543337,1.351039
3,Beni,General José Ballivián,Reyes,11016.0,12912.0,11284.0,1815.0,2962.0,3417.0,6.069421,4.359217,3.302312,1.443712,-1.123094,4.452539,1.190819
4,Beni,General José Ballivián,Santa Rosa,8915.0,9297.0,10953.0,1567.0,1976.0,2755.0,5.689215,4.704960,3.975681,0.381423,1.366014,2.108288,2.769524
5,Beni,Yacuma,Exaltación,6504.0,5996.0,7810.0,1090.0,938.0,1455.0,5.966972,6.392324,5.367698,-0.739316,2.202603,-1.365300,3.658427
6,Pando,Nicolás Suárez,Cobija,20873.0,43616.0,51908.0,4923.0,12304.0,15564.0,4.239894,3.544863,3.335132,6.699705,1.450407,8.327330,1.958635
7,Pando,Nicolás Suárez,Porvenir,3554.0,7653.0,9096.0,831.0,1655.0,2230.0,4.276775,4.624169,4.078924,6.972945,1.439475,6.262968,2.485005
8,Pando,Nicolás Suárez,Bolpebra,1137.0,2058.0,2338.0,292.0,545.0,802.0,3.893836,3.776147,2.915212,5.394013,1.063010,5.673018,3.219357
9,Pando,Nicolás Suárez,Bella Flor,2140.0,3550.0,3421.0,497.0,944.0,1235.0,4.305835,3.760593,2.770040,4.601289,-0.308456,5.832147,2.239167
10,Pando,Manuripi,Puerto Rico,3846.0,5639.0,6870.0,728.0,1382.0,1989.0,5.282967,4.080318,3.453997,3.478846,1.645478,5.827145,3.034169
11,Pando,Manuripi,San Pedro,1079.0,2987.0,3248.0,205.0,611.0,612.0,5.263415,4.888707,5.307190,9.256680,0.698082,9.928063,0.013628
12,Pando,Manuripi,Filadelfia,2800.0,5534.0,7993.0,590.0,1427.0,2514.0,4.745763,3.878066,3.179395,6.193559,3.063794,8.029155,4.719173
13,Pando,Madre de Dios,Puerto Gonzalo Moreno,3687.0,7544.0,11760.0,592.0,1026.0,1965.0,6.228041,7.352827,5.984733,6.508540,3.699595,4.999240,5.415204
14,Pando,Madre de Dios,San Lorenzo,3406.0,7058.0,9602.0,586.0,1342.0,1850.0,5.812287,5.259314,5.190270,6.623847,2.565081,7.532696,2.675205
15,Pando,Madre de Dios,Sena,2103.0,8161.0,10247.0,398.0,1653.0,2875.0,5.283920,4.937084,3.564174,12.327289,1.896819,12.944501,4.612174
16,Pando,Abuná,Santa Rosa,1815.0,2183.0,2827.0,278.0,611.0,860.0,6.528777,3.572831,3.287209,1.678315,2.154300,7.158871,2.848629
17,Pando,Abuná,Ingavi,867.0,1618.0,2545.0,162.0,344.0,649.0,5.351852,4.703488,3.921418,5.671883,3.774499,6.845867,5.289925
18,Pando,Federico Román,Nueva Esperanza,655.0,1777.0,1572.0,170.0,466.0,489.0,3.852941,3.813305,3.214724,9.073151,-1.021482,9.167156,0.401474
19,Pando,Federico Román,Villa Nueva,968.0,2787.0,2485.0,185.0,589.0,708.0,5.232432,4.731749,3.509887,9.613536,-0.955776,10.527912,1.533483
20,Pando,Federico Román,Santos Mercado,481.0,1969.0,2282.0,90.0,466.0,601.0,5.344444,4.225322,3.797005,12.812853,1.229387,14.948872,2.120078

## 4. Garde-fou

La somme des 21 municipalités doit égaler strictement la ligne "Amazonía Norte" pour pop et hh,
à chaque année. Tout écart signale une colonne mal repérée ou un filtre de lignes incorrect.

In [ ]:
for year in (2001, 2012, 2024):
    pop_sum = out[f"pop_{year}"].sum()
    pop_col = find_column(raw_columns, POP_BLOCK, year, POP_SUBCOL_BY_YEAR[year])
    pop_expected = float(total_row[pop_col].iloc[0])
    assert pop_sum == pop_expected == EXPECTED_POP_TOTALS[year], (
        f"pop_{year}: somme des 21 municipalités = {pop_sum}, "
        f"ligne 'Amazonía Norte' = {pop_expected}, attendu {EXPECTED_POP_TOTALS[year]}"
    )

    hh_sum = out[f"hh_{year}"].sum()
    hh_col = find_column(raw_columns, HH_BLOCK, year, HH_SUBCOL_BY_YEAR[year])
    hh_expected = float(total_row[hh_col].iloc[0])
    assert hh_sum == hh_expected == EXPECTED_HH_TOTALS[year], (
        f"hh_{year}: somme des 21 municipalités = {hh_sum}, "
        f"ligne 'Amazonía Norte' = {hh_expected}, attendu {EXPECTED_HH_TOTALS[year]}"
    )

print("Assertions OK : 21 municipalités retenues, sommes pop/hh = ligne 'Amazonía Norte' pour 2001/2012/2024.")

Assertions OK : 21 municipalités retenues, sommes pop/hh = ligne 'Amazonía Norte' pour 2001/2012/2024.