# Municipality Count — Norte Amazonia Bolivia

This notebook processes the **2024 Bolivian census data** to estimate the number of infrastructure
units (schools, health centers, shops, etc.) required in each municipality of the northern Amazon region.

Two output datasets are produced:

| Output file | Description |
|---|---|
| `municipalities_counts.csv / .xlsx` | Based on **non-electrified** households only (1 900-person threshold) |
| `municipalities_counts_total.csv` | Based on **all** 2024 households — full infrastructure need |

**Census source**: INE, *Censo Bolivia 2024 — Datos y Estadísticas Clave* (2025)  
**Allocation rules**: Arias thesis methodology (Lowlands)

In [46]:
import pandas as pd
import numpy as np

# ── Column name constants (long INE census headers) ─────────────────────────
COL_HH_GRID   = "NÚMERO DE VIVIENDAS POR FUENTE DE ELECTRICIDAD | 2024 | Servicio público de energía eléctrica"
COL_HH_MOTOR  = "NÚMERO DE VIVIENDAS POR FUENTE DE ELECTRICIDAD | 2024 | Motor propio"
COL_HH_SOLAR  = "NÚMERO DE VIVIENDAS POR FUENTE DE ELECTRICIDAD | 2024 | Panel solar"
COL_HH_OTHER  = "NÚMERO DE VIVIENDAS POR FUENTE DE ELECTRICIDAD | 2024 | Otra"
COL_HH_NO     = "NÚMERO DE VIVIENDAS POR FUENTE DE ELECTRICIDAD | 2024 | No tiene"
COL_PER_NO    = "NÚMERO DE PERSONAS POR FUENTE DE ELECTRICIDAD | 2024 | No tiene"
COL_PER_TOTAL = "NÚMERO DE PERSONAS POR FUENTE DE ELECTRICIDAD | 2024 | Total"

# ── Infrastructure allocation rules (Arias thesis, Lowlands methodology) ────
# Format: (output_column, units_per_n_households_or_persons, minimum_count)
INFRA_RULES_HH = [         # applied to household count
    ("public_lighting",        10,  0),
    ("store",                  30,  1),
    ("restaurant",             30,  1),
    ("workshop",               60,  1),
    ("entertainment_business", 60,  1),
    ("rice_processing",       200,  0),
]
INFRA_RULES_PER = [        # applied to person count
    ("school",        5000, 1),
    ("health_center", 5000, 1),
]
THRESHOLD_PERSONS = 1900   # min. non-electrified persons to justify a school/health center

## 1. Load census data

In [47]:
df = pd.read_csv("output/CSV_final.csv", sep=",")
print(f"Census data loaded: {df.shape[0]} rows × {df.shape[1]} columns")

Census data loaded: 29 rows × 124 columns

## 2. Clean data and build municipality identifiers

Drop aggregate rows where `MUNICIPIO/TIOC` is empty (these are regional summary rows, not individual municipalities).

Then build a clean `municipality` identifier in snake_case, with a department suffix to distinguish the two cities named **Santa Rosa** (one in Beni, one in Pando).

In [48]:
# Drop aggregate rows (empty MUNICIPIO/TIOC = regional summary rows, not individual municipalities)
df_clean = df.dropna(subset=["MUNICIPIO/TIOC"]).copy()

def build_municipality_id(row):
    """Snake_case municipality name, with department suffix to disambiguate duplicate names."""
    muni = str(row["MUNICIPIO/TIOC"]).strip()
    dept = str(row["DEPARTAMENTO"]).strip()
    if muni == "Santa Rosa":          # two cities share this name (Beni and Pando)
        return f"Santa_Rosa_{dept}"
    return muni.replace(" ", "_")

df_clean["municipality"] = df_clean.apply(build_municipality_id, axis=1)
df_clean["department"]   = df_clean["DEPARTAMENTO"]

## 3. Infrastructure allocation — non-electrified households

For each municipality, estimate the number of infrastructure units based solely on
**non-electrified** households and persons (census 2024, *"No tiene"* electricity source).

The rules come from the **Arias thesis (Lowlands methodology)**:

| Infrastructure | Based on | Rule |
|---|---|---|
| School | Persons without electricity | 1 per 5 000 persons, if ≥ 1 900 persons |
| Health center | Persons without electricity | 1 per 5 000 persons, if ≥ 1 900 persons |
| Public lighting | Non-electrified households | 1 per 10 hh |
| Store | Non-electrified households | 1 per 30 hh (min 1) |
| Restaurant | Non-electrified households | 1 per 30 hh (min 1) |
| Workshop | Non-electrified households | 1 per 60 hh (min 1) |
| Entertainment business | Non-electrified households | 1 per 60 hh (min 1) |
| Rice processing | Non-electrified households | 1 per 200 hh |

<div style="background:#d1ecf1; border-left:5px solid #17a2b8; padding:10px; border-radius:4px; margin:8px 0">
ℹ️ The 1 900-person threshold prevents allocating schools or health centers to very small
isolated communities where a shared facility would be more appropriate.
</div>

In [49]:
df_clean["non_elec_hh"]     = df_clean[COL_HH_NO].fillna(0).astype(int)
df_clean["persons_no_elec"] = df_clean[COL_PER_NO].fillna(0).astype(int)

# Household-based allocations (vectorized)
for col, ratio, min_val in INFRA_RULES_HH:
    df_clean[col] = np.maximum(min_val, df_clean["non_elec_hh"] // ratio)

# Person-based allocations — apply threshold to skip very small communities
for col, ratio, min_val in INFRA_RULES_PER:
    counts = np.maximum(min_val, df_clean["persons_no_elec"] // ratio)
    df_clean[col] = np.where(df_clean["persons_no_elec"] >= THRESHOLD_PERSONS, counts, 0)

OUTPUT_COLS = [
    "department", "municipality", "non_elec_hh", "persons_no_elec",
    "school", "health_center", "public_lighting", "store", "restaurant",
    "workshop", "entertainment_business", "rice_processing",
]
df_nonelec = df_clean[OUTPUT_COLS].sort_values(["department", "municipality"])

numeric_cols = df_nonelec.select_dtypes(include="number").columns
total_row = df_nonelec[numeric_cols].sum().to_frame().T
total_row["department"]   = "Amazonia_Norte"
total_row["municipality"] = "TOTAL"

df_out_nonelec = pd.concat([df_nonelec, total_row], ignore_index=True)
df_out_nonelec

,department,municipality,non_elec_hh,persons_no_elec,school,health_center,public_lighting,store,restaurant,workshop,entertainment_business,rice_processing
0,Beni,Exaltación,273,1291,0,0,27,9,9,4,4,1
1,Beni,Guayaramerín,825,2373,1,1,82,27,27,13,13,4
2,Beni,Reyes,711,1991,1,1,71,23,23,11,11,3
3,Beni,Riberalta,2925,9103,1,1,292,97,97,48,48,14
4,Beni,Santa_Rosa_Beni,407,1583,0,0,40,13,13,6,6,2
5,La Paz,Ixiamas,1043,3480,1,1,104,34,34,17,17,5
6,Pando,Bella_Flor,351,751,0,0,35,11,11,5,5,1
7,Pando,Bolpebra,253,663,0,0,25,8,8,4,4,1
8,Pando,Cobija,395,1077,0,0,39,13,13,6,6,1
9,Pando,Filadelfia,594,1603,0,0,59,19,19,9,9,2
10,Pando,Ingavi,261,860,0,0,26,8,8,4,4,1
11,Pando,Nueva_Esperanza,151,442,0,0,15,5,5,2,2,0
12,Pando,Porvenir,213,693,0,0,21,7,7,3,3,1
13,Pando,Puerto_Gonzalo_Moreno,348,2116,1,1,34,11,11,5,5,1
14,Pando,Puerto_Rico,325,1078,0,0,32,10,10,5,5,1
15,Pando,San_Lorenzo,302,1462,0,0,30,10,10,5,5,1
16,Pando,San_Pedro,369,2008,1,1,36,12,12,6,6,1
17,Pando,Santa_Rosa_Pando,149,378,0,0,14,4,4,2,2,0
18,Pando,Santos_Mercado,208,684,0,0,20,6,6,3,3,1
19,Pando,Sena,1073,3375,1,1,107,35,35,17,17,5
20,Pando,Villa_Nueva,213,698,0,0,21,7,7,3,3,1
21,Amazonia_Norte,TOTAL,11389,37709,7,7,1130,369,369,178,178,47

## 4. Export — non-electrified municipalities

Add a `TOTAL` summary row (sum of all numeric columns) and save to both CSV and Excel.

In [50]:
df_out_nonelec.to_csv("output/municipalities_counts.csv",    index=False)
df_out_nonelec.to_excel("output/municipalities_counts.xlsx", index=False)

print(f"Saved {len(df_out_nonelec) - 1} municipalities + TOTAL row.")

Saved 21 municipalities + TOTAL row.

## 5. Full population totals (all households)

A second dataset uses **all 2024 households** (regardless of electricity source) and **total population**, without the 1 900-person threshold. This represents the full infrastructure need for the municipality, not just the non-electrified fraction.

| Infrastructure | Based on | Rule |
|---|---|---|
| School | Total persons | 1 per 5 000 persons (min 1, no threshold) |
| Health center | Total persons | 1 per 5 000 persons (min 1, no threshold) |
| Public lighting | Total households | 1 per 10 hh |
| Store | Total households | 1 per 30 hh (min 1) |
| Restaurant | Total households | 1 per 30 hh (min 1) |
| Workshop | Total households | 1 per 60 hh (min 1) |
| Entertainment business | Total households | 1 per 60 hh (min 1) |
| Rice processing | Total households | 1 per 200 hh |

Saved to `output/municipalities_counts_total.csv`.

In [51]:
ALL_HH_COLS = [COL_HH_GRID, COL_HH_MOTOR, COL_HH_SOLAR, COL_HH_OTHER, COL_HH_NO]
df_clean["total_hh"]      = df_clean[ALL_HH_COLS].sum(axis=1).astype(int)
df_clean["total_persons"] = df_clean[COL_PER_TOTAL].fillna(0).astype(int)

df_total = df_clean.copy()

for col, ratio, min_val in INFRA_RULES_HH:
    df_total[col] = np.maximum(min_val, df_total["total_hh"] // ratio)

for col, ratio, min_val in INFRA_RULES_PER:
    df_total[col] = np.maximum(min_val, df_total["total_persons"] // ratio)

OUTPUT_COLS_TOTAL = [
    "department", "municipality", "total_hh", "total_persons",
    "school", "health_center", "public_lighting",
    "store", "restaurant", "workshop",
    "entertainment_business", "rice_processing",
]
df_total = df_total[OUTPUT_COLS_TOTAL].sort_values(["department", "municipality"])

numeric_cols_t = df_total.select_dtypes(include="number").columns
total_row_t = df_total[numeric_cols_t].sum().to_frame().T
total_row_t["department"]   = "Amazonia_Norte"
total_row_t["municipality"] = "TOTAL"

df_out_total = pd.concat([df_total, total_row_t], ignore_index=True)
df_out_total.to_csv("output/municipalities_counts_total.csv", index=False)

print(f"Saved {len(df_out_total) - 1} municipalities + TOTAL row.")
df_out_total.tail(5)

Saved 21 municipalities + TOTAL row.

,department,municipality,total_hh,total_persons,school,health_center,public_lighting,store,restaurant,workshop,entertainment_business,rice_processing
17,Pando,Santa_Rosa_Pando,860,2827,1,1,86,28,28,14,14,4
18,Pando,Santos_Mercado,601,2282,1,1,60,20,20,10,10,3
19,Pando,Sena,2875,10247,2,2,287,95,95,47,47,14
20,Pando,Villa_Nueva,708,2485,1,1,70,23,23,11,11,3
21,Amazonia_Norte,TOTAL,84209,317517,62,62,8412,2796,2796,1393,1393,413

## 6. Source B — off-grid electrified households

These are households that have their own electricity source — a motor/genset, solar panels,
or something else — but **are not connected to the public grid**.
They are separate from Source A (grid-connected) and from Section 3 (no electricity at all).

The rules are mostly the same as Section 3, with three differences:

| Infrastructure | Based on | Rule |
|---|---|---|
| School | Real count from `northern_amazon_education_health_final.csv` | Scaled by the off-grid share of households |
| Health center | — | **0 for all municipalities** — health posts need stable grid power, so they always fall under Source A |
| Public lighting | — | **0 for all municipalities** — street lighting runs on the public grid |
| Store | Off-grid households | 1 per 30 hh (min 1) |
| Restaurant | Off-grid households | 1 per 30 hh (min 1) |
| Workshop | Off-grid households | 1 per 60 hh (min 1) |
| Entertainment business | Off-grid households | 1 per 60 hh (min 1) |
| Rice processing | Off-grid households | 1 per 200 hh |

Saved to `output/municipalities_counts_sourceB.csv`.

In [52]:
df_clean["hh_sourceB"] = (
    df_clean[COL_HH_MOTOR].fillna(0) +
    df_clean[COL_HH_SOLAR].fillna(0) +
    df_clean[COL_HH_OTHER].fillna(0)
).astype(int)

# Total households and total persons per municipality
all_hh_cols = [COL_HH_GRID, COL_HH_MOTOR, COL_HH_SOLAR, COL_HH_OTHER, COL_HH_NO]
tot_hh      = df_clean[all_hh_cols].fillna(0).sum(axis=1).astype(int)
tot_persons = df_clean[COL_PER_TOTAL].fillna(0).astype(int)

# The census has no separate person count for off-grid households,
# so we estimate proportionally from the total population.
df_clean["persons_sourceB"] = (
    tot_persons * df_clean["hh_sourceB"] / tot_hh
).round().astype(int)

print(f"Off-grid households (total):        {df_clean['hh_sourceB'].sum():,}")
print(f"Off-grid persons (estimated total): {df_clean['persons_sourceB'].sum():,}")

Off-grid households (total):        9,325
Off-grid persons (estimated total): 36,167

Now load the real school counts from the education file and scale them down to the off-grid share of households.

In [53]:
edu = pd.read_csv("data/northern_amazon_education_health.csv")
SCHOOL_COL = "Schools"

# Match education file rows to municipality IDs.
# We use Department + Municipality together so the two "Santa Rosa" towns don't get mixed up.
key_to_id = {
    (str(row["DEPARTAMENTO"]).strip(), str(row["MUNICIPIO/TIOC"]).strip()): row["municipality"]
    for _, row in df_clean.iterrows()
}

edu["municipality"] = edu.apply(
    lambda r: key_to_id.get((str(r["Department"]).strip(), str(r["Municipality/TIOC"]).strip())),
    axis=1,
)

unmatched = edu[edu["municipality"].isna()]["Municipality/TIOC"].tolist()
if unmatched:
    print(f"WARNING — could not match these municipalities: {unmatched}")

# School count per municipality (NaN where data is missing)
schools_total = edu.set_index("municipality")[SCHOOL_COL]

# Total households per municipality, needed to compute the off-grid share
all_hh_cols = [COL_HH_GRID, COL_HH_MOTOR, COL_HH_SOLAR, COL_HH_OTHER, COL_HH_NO]
tot_hh = df_clean[all_hh_cols].fillna(0).sum(axis=1).astype(int)


def school_count_sourceB(row):
    total_schools = schools_total.get(row["municipality"], np.nan)
    if pd.isna(total_schools):
        return np.nan   # no data available for this municipality
    return round(total_schools * row["hh_sourceB"] / tot_hh[row.name])


df_clean["school_sourceB"] = df_clean.apply(school_count_sourceB, axis=1)

missing = df_clean[df_clean["school_sourceB"].isna()]["municipality"].tolist()
if missing:
    print(f"No school data for: {missing}")
    print("These will appear as NaN in the output.")

Apply the full allocation rules, add a TOTAL row, and save to CSV.

In [54]:
df_sb = df_clean[["department", "municipality", "hh_sourceB", "persons_sourceB"]].copy()

# Health centers and public lighting: always 0 for off-grid
# (both need reliable grid power and fall under Source A)
df_sb["health_center"]  = 0
df_sb["public_lighting"] = 0

# Schools: real data, scaled by off-grid share (NaN kept where data is missing)
df_sb["school"] = df_clean["school_sourceB"]

# Everything else: same Arias ratios as Section 3, applied to off-grid households
for col, ratio, min_val in INFRA_RULES_HH:
    if col == "public_lighting":
        continue
    df_sb[col] = np.maximum(min_val, df_sb["hh_sourceB"] // ratio)

OUTPUT_COLS_SB = [
    "department", "municipality", "hh_sourceB", "persons_sourceB",
    "school", "health_center", "public_lighting",
    "store", "restaurant", "workshop", "entertainment_business", "rice_processing",
]
df_sb = df_sb[OUTPUT_COLS_SB].sort_values(["department", "municipality"])

# Add a TOTAL row
numeric_cols = df_sb.select_dtypes(include="number").columns
total_row = df_sb[numeric_cols].sum(min_count=1).to_frame().T
total_row["department"]   = "Amazonia_Norte"
total_row["municipality"] = "TOTAL"

df_out_sb = pd.concat([df_sb, total_row], ignore_index=True)

df_out_sb.to_csv("output/municipalities_counts_sourceB.csv", index=False)
print(f"Saved {len(df_out_sb) - 1} municipalities + TOTAL row.\n")

totrow = df_out_sb[df_out_sb["municipality"] == "TOTAL"].iloc[0]
print(f"Off-grid households (total):        {int(totrow['hh_sourceB']):,}")
print(f"Off-grid persons (estimated total): {int(totrow['persons_sourceB']):,}")
print()
df_out_sb

Saved 21 municipalities + TOTAL row.

Off-grid households (total):        9,325
Off-grid persons (estimated total): 36,167

,department,municipality,hh_sourceB,persons_sourceB,school,health_center,public_lighting,store,restaurant,workshop,entertainment_business,rice_processing
0,Beni,Exaltación,890,4777,12,0,0,29,29,14,14,4
1,Beni,Guayaramerín,646,2380,5,0,0,21,21,10,10,3
2,Beni,Reyes,353,1166,6,0,0,11,11,5,5,1
3,Beni,Riberalta,1396,5485,6,0,0,46,46,23,23,6
4,Beni,Santa_Rosa_Beni,620,2465,6,0,0,20,20,10,10,3
5,La Paz,Ixiamas,793,2718,12,0,0,26,26,13,13,3
6,Pando,Bella_Flor,315,873,4,0,0,10,10,5,5,1
7,Pando,Bolpebra,393,1146,8,0,0,13,13,6,6,1
8,Pando,Cobija,248,827,1,0,0,8,8,4,4,1
9,Pando,Filadelfia,608,1933,10,0,0,20,20,10,10,3
10,Pando,Ingavi,275,1078,6,0,0,9,9,4,4,1
11,Pando,Nueva_Esperanza,267,858,5,0,0,8,8,4,4,1
12,Pando,Porvenir,217,885,3,0,0,7,7,3,3,1
13,Pando,Puerto_Gonzalo_Moreno,232,1388,2,0,0,7,7,3,3,1
14,Pando,Puerto_Rico,320,1105,8,0,0,10,10,5,5,1
15,Pando,San_Lorenzo,260,1349,4,0,0,8,8,4,4,1
16,Pando,San_Pedro,241,1279,4,0,0,8,8,4,4,1
17,Pando,Santa_Rosa_Pando,143,470,3,0,0,4,4,2,2,0
18,Pando,Santos_Mercado,205,778,4,0,0,6,6,3,3,1
19,Pando,Sena,682,2431,11,0,0,22,22,11,11,3
20,Pando,Villa_Nueva,221,776,5,0,0,7,7,3,3,1
21,Amazonia_Norte,TOTAL,9325,36167,125,0,0,300,300,146,146,38